version:  '3'

services:

  api:
    image:      'guimaron/tvmaze-api'
    mem_limit:  128m
    hostname:   api

  frontend:
    image:      'guimaron/tvmaze-frontend'
    mem_limit:  128m
    hostname:   frontend 
    depends_on:
      - api

  nginx:
    image:    'guimaron/tvmaze-nginx'
    restart:  always
    ports:
      - '80:80'
    mem_limit:  128m
    hostname:   nginx
    depends_on:
      - api
      - frontend
