version:  '3'

services:
 
  redis:
    image:  'redis:latest'
    ports:
      - '6379:6379'

  api:
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './api'
    volumes:
      - './api:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - '5000:5000'
    depends_on:
      - redis

  frontend:
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './frontend'
    environment:
      - WDS_SOCKET_PORT=0    
    volumes:
      - './frontend:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - api

  nginx:
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './nginx'
    restart:  always
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
