version:  '3'

services:

  redis:
    image:      'redis:latest'
    restart:    always
    mem_limit:  128m
    hostname:   redis

  api:
    image:      'guimaron/tvmaze-api'
    mem_limit:  128m
    restart:    always
    hostname:   api
    ports:
      - '5000:5000'
    depends_on:
      - redis

  frontend:
    image:      'guimaron/tvmaze-frontend'
    mem_limit:  128m
    hostname:   frontend 
    depends_on:
      - api

  nginx:
    image:    'guimaron/tvmaze-nginx'
    restart:  always
    ports:
      - '80:80'
    mem_limit:  128m
    hostname:   nginx
    depends_on:
      - api
      - frontend
