version:  '3'

services:
 
  redis:
    hostname: redis
    image:    'redis:latest'

  api:
    hostname:     api
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './api'
    restart:  always
    volumes:
      - './api:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - '5000:5000'
    depends_on:
      - redis

  frontend:
    hostname:     frontend
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './frontend'
    environment:
      - WDS_SOCKET_PORT=0    
    volumes:
      - './frontend:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - api

  tests:
    hostname:     tests
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './frontend' 
    volumes:
      - './frontend:/usr/app'
      - '/usr/app/node_modules'
    command:  ["npm", "run", "test"]
    depends_on:
      - api

  nginx:
    hostname:     nginx
    build:
      dockerfile: 'Dockerfile.dev'
      context:    './nginx'
    restart:  always
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
