version:  '3'

services:
 
  redis:
    hostname:   redis
    image:    'redis:latest'

  api:
    hostname:     api
    build:
      dockerfile: 'Dockerfile'
      context:    './api'
    restart:  always
    volumes:
      - './api:/usr/app'
      - '/usr/app/node_modules'
    depends_on:
      - redis

  frontend:
    hostname:     frontend
    build:
      dockerfile: 'Dockerfile'
      context:    './frontend'
    volumes:
      - './frontend:/usr/app'
      - '/usr/app/node_modules'
    depends_on:
      - api

  nginx:
    hostname:     nginx
    build:
      dockerfile: 'Dockerfile'
      context:    './nginx'
    restart:  always
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
